import React, { useEffect } from "react";
import Header from "./Header";
import Footer from "./Footer";

const Greencrackers = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <>
      <Header />
      <section className="my-5">
        <div className="container">
          <h2> Green Crackers</h2>
          <p>
            Diwali is one of the few celebrations that brings the country
            together. It's about celebrating the triumph of good against evil.
            The celebration of good over evil cannot contain anything bad.
          </p>
          <p>
            However, there has been a recent outrage over the pollution
            generated by Diwali crackers. There may be some pollution tonight as
            a result of the crackers that are set off during Diwali. However, we
            are called to consider this assertion in light of everything else
            going on in our lives and around the world.
          </p>
          <p>
            The pollution created during Diwali is primarily due to the music
            and smoke. It is important to understand that the smoke produced by
            the crackers is sulphur smoke rather than carbon smoke. Remember in
            the early 1990s, when it would rain for a few days during Diwali?
            This was solely because of the sulphur smoke produced by the
            crackers. Sulphur is a natural rain-creating agent that helps to
            chill the land after Diwali.
          </p>
          <p>
            Given that the cracker industry benefits many families and the
            sulphur smokes only generate beneficial things like rain, Diwali is
            clearly not a cause of pollution.
          </p>
          <p>
            The amount of pollution created during Diwali is negligible when
            compared to the pollution caused by vehicles, power plants, garbage
            burning, and a variety of other activities that occur all year. The
            pollution caused by Diwali crackers accounts for less than 0.1% of
            the total contribution of other pollutants. When we talk about
            pollution-free Diwali, we don't always mean a cracker-free Diwali.
          </p>
          <p>
            It must be acknowledged that some crackers manufactured without
            adhering to the chemical quality criteria and composition mandated
            for pyrotechnics may result in slightly greater pollution than
            planned. This could have a negative impact on the environment as
            well as the workers who make these crackers. However, with
            manufacturers adhering to the highest quality standards and
            retailers like Srivatsaa Celebrations making cracker quality one of
            the most important requirements for inclusion in their inventory,
            you can be confident that Diwali celebrations with crackers will
            only get better for the environment and not worse!
          </p>
        </div>
      </section>
      <Footer />
    </>
  );
};

export default Greencrackers;
