import React, { useEffect } from "react";

const TermsandConditions = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <>
      <section className="my-5">
        <div className="container">
          <h3>Terms & Conditions </h3>
          <p>
            These terms and conditions apply to www.Srivatsaacelebrations.com/
            and the buyers or users of this website. We encourage that all users
            carefully read the terms and conditions before using or enrolling on
            the website, or accessing any material, information, or services
            available through the website. Your use of this website or the
            services provided by it constitutes your acceptance of the terms and
            conditions and your commitment to be legally bound by them. "We
            won't invite any Returns"
          </p>
          <h5>FRIEGHT CHARGES EXTRA</h5>
          <p>
            Any document produced using this website,
            www.Srivatsaacelebrations.com/, will be generated by an electronic
            system. It means that any document created as an electronic record
            under the Information Technology Act of 2000 does not require an
            electronic or physical signature.
          </p>
          <h5>
            YOUR USE OF THE WEBSITE IMPLIES THAT YOU AGREE WITH THE TERMS OF
            USE.
          </h5>
          <h5>A) GENERAL</h5>
          <p>
            A.1 www.Srivatsaacelebrations.com/ ("Website") is an Internet-based
            portal owned and controlled by Srivatsaacelebrations Crackers, a
            company incorporated under the laws of India, with its registered
            office at 1/51C, North Street, Vadamalapuram,Sivakasi-626130. GST:
            ……………………….. Use of the Website is conditioned on acceptance of all
            the terms, conditions, and notices contained in these Terms, as well
            as amendments made by Srivatsaacelebrations Crackers at its sole
            discretion and posted on the Website, including the imposition of an
            additional charge for access to or use of a Service.
          </p>
          <p>
            A.2 www.Srivatsaacelebrations.com/ is not required to notify you,
            whether registered or not, of any modifications to the Terms of Use.
            The amended Terms of Use will be made available on the Website. Your
            use of the Website and Services is subject to the most recent
            version of the Terms of Use that is published on the website at the
            time of use. To view the most recent Terms of Use, please visit the
            home page at www.Srivatsaacelebrations.com/ on a frequent basis. The
            "Last Updated" legend below indicates when the Terms of Use were
            last amended.It is your obligation to routinely check these Terms of
            Use for updates. www.Srivatsaacelebrations.com/ may ask you to
            submit your assent to the amended Terms of Use in a specific manner
            prior to any continued use of the Website or the Services provided
            on the Website. If no such separate consent is obtained, your
            continuing use of the Website following modifications to the Terms
            of Use constitutes acceptance of those changes.
          </p>
          <p>
            A.3 By using this website or any facility or service provided by
            this website in any way, or simply viewing the website, you confirm
            that you have read, understood, and accepted to be governed by these
            Terms and Conditions and the website's Privacy Policy, which is
            available on the homepage.
          </p>
          <p>
            A.4 www.Srivatsaacelebrations.com/ promises to deliver the product
            requested by you only to the locations specified in the delivery
            chart. www.Srivatsaacelebrations.com/ is not obligated to provide
            any merchandise or services purchased by Users for delivery to areas
            outside of India.
          </p>
          <p>
            A.5 If a product is not available at the time of delivery, we will
            automatically update your order with other related products.
          </p>
          <h5>B. COMMUNICATION</h5>
          <p>
            B.1 You expressly consent to receive communications via SMS and
            e-mail from Srivatsaacelebrations@gmail.com regarding services
            supplied through the website. www.Srivatsaacelebrations.com/
          </p>
          <p>
            B.1A: OUR CUSTOMER SUPPORT WHATSAPP TEXT MESSAGE NUMBER: 9043360340
            (REPLY TIME-10 AM-6.30 PM)
          </p>
          <p>
            B.2 Users can unsubscribe from receiving communications via email.
          </p>
          <p>
            B.3 All notices to www.Srivatsaacelebrations.com/ will be served via
            email or general announcement on the website alone. Any notice made
            to www.Srivatsaacelebrations.com/ in accordance with the Terms and
            Conditions shall be emailed to Srivatsaacelebrations@gmail.com
            customer support.
          </p>
          <p>
            B.4 You may not assign or otherwise transfer the terms and
            conditions or any rights granted hereunder to any third party.
            www.Srivatsaacelebrations.com/ has the right, under the Terms and
            Conditions, to freely transfer to any third party without your
            approval.
          </p>
          <p>
            B.5 If, for any reason, a court of competent jurisdiction finds any
            provision of the Terms of Use, or portion thereof, to be
            unenforceable, that provision shall be enforced to the maximum
            extent permissible so as to give effect to the parties' intent as
            reflected by that provision, and the remainder of the Terms of Use
            shall remain in full force.
          </p>
          <h5>C. SERVICES</h5>
          <p>
            C.1 The Website is a platform that allows for the online sale and
            purchase of "MULTI brand" crackers and services provided by
            www.Srivatsaacelebrations.com/ different affiliate/registered
            merchants/vendors/service providers at a reduced price. The Services
            are provided to Users through a variety of channels, including the
            distribution of coupons and vouchers that can be redeemed for
            various services. The Terms of Offer For Sale ("Terms of Offer For
            Sale") shall govern the purchase of products and services on the
            website.
          </p>
          <h5>D. ELIGILIBITY FOR USE</h5>
          <p>
            D.1The Services are not available to minors under the age of
            eighteen (18), or to Users who have been suspended or removed from
            the www.Srivatsaacelebrations.com/ system for any reason. If you do
            not meet the requirements outlined above, you will be unable to use
            the Services or the Website. You represent that you are of legal age
            to enter into a binding contract and are not prohibited from getting
            services under Indian law. Regardless of the foregoing, if you are
            under the age of eighteen (18), you may use the Services offered by
            www.Srivatsaacelebrations.com/ through your legal guardian in
            accordance with applicable laws.
          </p>
          <p>
            D.2 www.Srivatsaacelebrations.com/ reserves the right to refuse
            access to the Website's Services to new Users or to terminate access
            granted to existing Users at any time without providing a reason.
          </p>
          <p>
            D.3 You cannot have more than one active Account on the Website.
            Furthermore, you are not permitted to sell, trade, or otherwise
            transfer Your Account to another party.
          </p>
          <h5>E. USER ACCOUNT, PASSWORD AND SECURITY</h5>
          <p>
            E.1 www.Srivatsaacelebrations.com/ makes the Services available to
            you through the website only if you have provided
            www.Srivatsaacelebrations.com/ with certain required User
            information and created an account ("Account") using a password or
            other log-in ID and password, which can include a Facebook, Gmail,
            Yahoo ID, or any other valid email ID (collectively, the "Account
            Information"). The Services may also be subject to Website use
            procedures, Terms of Offer For Sale, uploading guidelines, rules,
            additional terms of service, or other disclaimers and notifications,
            as applicable ("Additional Terms"). If the Terms and Conditions
            contradict, the Additional Terms will take precedence in relation to
            that service.
          </p>
          <p>
            E.2 In order to use the Website's Services, you must first register
            as a User and create an Account. You shall be solely responsible for
            maintaining the confidentiality of the Account Information and for
            any actions that occur under Your Account. You agree to immediately
            alert www.Srivatsaacelebrations.com/ of any unauthorized use of your
            Account information or any other breach of security, and to log out
            of your account at the conclusion of each session.
            www.Srivatsaacelebrations.com/ cannot and will not be held liable
            for any losses or damages resulting from your failure. You may be
            held liable for losses incurred by www.Srivatsaacelebrations.com/ or
            any other user or visitor to the website as a result of authorized
            or unauthorized use of your account caused by your failure to keep
            your account information private and confidential.
          </p>
          <p>
            E.3 Unregistered Users might also have restricted access to the
            Website's services.
          </p>
          <p>
            E.4 You must ensure that the account information you give on the
            website's registration form is complete, accurate, and up to date.
            Use of another user's Account Information to access the Services is
            expressly banned.
          </p>
          <p>
            E.5 If You provide any information that is false, inaccurate, out of
            date, or incomplete (or becomes false, inaccurate, out of date, or
            incomplete), or if www.Srivatsaacelebrations.com/ has reasonable
            grounds to believe that such information is false, inaccurate, out
            of date, or incomplete, www.Srivatsaacelebrations.com/ reserves the
            right to suspend or terminate Your Account and refuse any and all
            current or future use of the Website (or any portion thereof).
          </p>
          <h5>F. PRICING INFORMATION</h5>
          <p>
            F.1 www.Srivatsaacelebrations.com/ attempts to provide you with the
            best available rates on products and services purchased or obtained
            through the website. The pricing information for purchasing products
            and services from the Website is outlined in the Terms of Offer For
            Sale.
          </p>
          <p>
            F.2 You agree to give valid and accurate credit/debit card
            information to the approved payment gateway when using the Website's
            Services. You may not use a credit/debit card that you do not
            lawfully possess; in other words, you must use Your own credit/debit
            card in all transactions. The information you give will not be used
            or shared with any third parties unless required for fraud
            verification or by law, regulation, or court order. You shall be
            solely responsible for the security and confidentiality of your
            credit or debit card information. www.Srivatsaacelebrations.com/
            specifically disclaims any liability that may occur as a result of
            the unauthorized use of your credit or debit card.
          </p>
          <p>
            F.3 www.Srivatsaacelebrations.com/ or Srivatsaacelebrations Crackers
            shall have no liability for any loss or damage arising directly or
            indirectly from the decline of authorization for any transaction due
            to you/cardholder exceeding the preset limit mutually agreed upon by
            www.Srivatsaacelebrations.com/ and our acquiring bank from time to
            time.
          </p>
          <h5>G. USER OBLIGATION:</h5>
          <p>
            G.1 Subject to your compliance with the Terms of Use,
            www.Srivatsaacelebrations.com/ grants you a non-exclusive, limited
            right to access and use this Website and the services it offers.
          </p>
          <p>
            G.2 You undertake to use the Services, Website, and materials
            exclusively for the reasons specified in the terms and conditions,
            as well as any applicable law, regulation, or generally accepted
            practices or recommendations in the relevant jurisdictions.
          </p>
          <p>
            G.3 You undertake to follow all limitations on the dissemination,
            use, and duplication of any materials available on the website.
          </p>
          <p>
            G.4 You agree not to access the website, materials, or services
            using any means other than the interface provided by
            www.Srivatsaacelebrations.com/. You shall not use any program,
            algorithm, or methodology, or any similar or equivalent manual
            process, to access, acquire, copy, or monitor any portion of the
            website or Content, or to reproduce or circumvent the navigational
            structure or presentation of the Website, materials, or any Content,
            in order to obtain or attempt to obtain any materials, documents, or
            information through any means not expressly provided through the
            website.
          </p>
          <p>
            G.5 You understand and accept that by accessing or using the website
            or Services, you may be exposed to content from other users that you
            find offensive, indecent, or otherwise
            objectionable.www.Srivatsaacelebrations.com/ disclaims all liability
            deriving from such offensive content on its website.
          </p>
          <p>
            G.6 If the Website permits you to post and upload material on the
            Website, you agree to guarantee that such material is not offensive
            and complies with applicable laws. Furthermore, you agree not to:
            defame, abuse, harass, threaten, or otherwise violate the legal
            rights of others; impersonate any person or entity, or falsely state
            or otherwise misrepresent your affiliation with a person or entity;
            or publish, post, upload, distribute, or disseminate any
            inappropriate, profane, defamatory, infringing, obscene, indecent,
            or unlawful topic, name, material, or information via any bookmark,
            tag, or keyword. Upload or distribute files containing viruses,
            corrupted files, or any other similar software or programs that may
            interfere with the Website's or another person's computer. Engage in
            any behavior that impedes or disrupts access to the Website or the
            Services. Collect or keep information about other users in
            connection with the banned conduct and activities outlined in this
            section.
          </p>
          <p>
            Use the Website or any material or Content for any unlawful or
            prohibited purpose under these Terms of Use, or to solicit the
            performance of any illegal or other action that violates the rights
            of www.Srivatsaacelebrations.com/ or any third parties.
          </p>
          <h5>H. USE OF WEBSITE</h5>
          <p>
            H.1 www.Srivatsaacelebrations.com/ now grants you non-exclusive,
            freely revocable, and non-transferable access to read, download, and
            print product catalogs or other materials available on the Website,
            subject to the following terms:
          </p>
          <p>
            H1 a) You may only access and use the resources for personal,
            informative, and internal reasons, in accordance with the Terms of
            Use.
          </p>
          <p>
            H1 b) You may not change or modify any product catalogs or other
            materials available on the Website.
          </p>
          <p>
            H1 c) You are not permitted to distribute or sell, rent, lease,
            license, or otherwise make the product catalogs or other items
            available on the Website available to others.
          </p>
          <p>
            H1 d) You are not permitted to delete any language, copyright, or
            other proprietary notices found in the product catalogs or other
            items available on the Website.
          </p>
          <h5>I. INTELLECTUAL PROPERTY RIGHTS</h5>
          <p>
            I.1 The Website and the processes, and their selection and
            arrangement, including but not limited to all text, graphics, user
            interfaces, visual interfaces, sounds and music, artwork and
            computer code on the website is owned and controlled by
            www.Srivatsaacelebrations.com/, and the design, structure,
            selection, coordination, expression, look and feel, and arrangement
            of such content is protected by copyright, patent, and trademark
            laws, as well as various other intellectual property
          </p>
          <p>
            I.2 The trademarks, logos, and service marks displayed on this
            website are the property of www.Srivatsaacelebrations.com/, their
            vendors, or other third parties. You are not entitled to use the
            marks without the prior approval of the vendor or any third party
            who may hold the marks.
          </p>
          <h5>J. DISCLAIMER OF WARRANTY & LIABILITY</h5>
          <p>
            J.1 The website www.Srivatsaacelebrations.com/ provides services and
            other materials on an as-is basis, which means there are no
            warranties for the following:
          </p>
          <p>
            J.1 a) The website or services will fulfill your needs, or your use
            of the website or services will be uninterrupted, timely, secure, or
            error-free.
          </p>
          <p>
            J.1 b) The results achieved from using the website, services, or
            materials will be effective, accurate, or reliable.
          </p>
          <p>
              J.1 c) The website, services, or materials will fulfill your
            standards.
          </p>
          <p>
            J.1 d) We, at www.Srivatsaacelebrations.com/, shall not be liable
            for any loss you may suffer as a result of unauthorized use of your
            account or account information in connection with the website or its
            services or materials, whether with or without your knowledge. J1e)
            We will not be liable for any non-availability of the website during
            periodic maintenance operations, or for any unforeseen suspension of
            access to the website caused by technical issues or other factors
            without our control.
          </p>
          <h5>K. INDEMNIFICATION AND LIMITATION OF LIABILITY</h5>
          <p>
            K.1 You agree to indemnify, defend and hold harmless
            www.Srivatsaacelebrations.com/ including but not limited to its
            affiliate vendors, agents and employees from and against any and all
            losses, liabilities, claims, damages, demands, costs and expenses
            (including legal fees and disbursements in connection therewith and
            interest chargeable thereon) asserted against or incurred by
            www.Srivatsaacelebrations.com/ that arise out of, result from, or
            may be payable by virtue of, any breach or non-performance of any
            representation, warranty, covenant or agreement made or obligation
            to be performed by You pursuant to these Terms of Use. Further, You
            agree to hold www.Srivatsaacelebrations.com/ or
            Srivatsaacelebrations Crackers Park harmless against any claims made
            by any third party due to, or arising out of, or in connection with,
            Your use of the Website, any claim that Your material caused damage
            to a third party, Your violation of the Terms of Use, or Your
            violation of any rights of another, including any intellectual
            property rights.
          </p>
          <p>
            K.2 In no event shall www.Srivatsaacelebrations.com/ or
            Srivatsaacelebrations Crackers, its officers, directors, employees,
            partners or suppliers be liable to You, the vendor or any third
            party for any special, incidental, indirect, consequential or
            punitive damages whatsoever, including those resulting from loss of
            use, data or profits, whether or not foreseeable or whether or not
            www.Srivatsaacelebrations.com/ has been advised of the possibility
            of such damages, or based on any theory of liability, including
            breach of contract or warranty, negligence or other tortuous action,
            or any other claim arising out of or in connection with Your use of
            or access to the Website, Services or materials.
          </p>
          <h5>L. VIOLATION OF TERMS AND CONDITIONS</h5>
          <p>
            L.1 You agree that www.Srivatsaacelebrations.com/ may, in its sole
            discretion and without prior notice, terminate your access to the
            website and block your future access to the Website if we at
            www.Srivatsaacelebrations.com/ determines that You have violated
            these terms and conditions or additional terms. You also agree that
            any violation by you of these terms and conditions will constitute
            an unlawful and unfair business practice, and will cause irreparable
            harm to www.Srivatsaacelebrations.com/ , for which monetary damages
            would be inadequate, and you consent to
            www.Srivatsaacelebrations.com obtaining any disjunctive or equitable
            relief that www.Srivatsaacelebrations.com deems necessary or
            appropriate in such circumstances. These remedies are in addition to
            any other remedies www.Srivatsaacelebrations.com/ may have at law or
            in equity.
          </p>
          <p>
            L.2 You agree that www.Srivatsaacelebrations.com/ may, in its sole
            discretion, and without prior notice, terminate or modify or correct
            or change or remove the information or material of the website or
            any service offered on or through the website at any time.
          </p>
          <p>
            L.3 If we at www.Srivatsaacelebrations.com/ or Srivatsaacelebrations
            does take any legal action against You as a result of Your violation
            of these terms & Conditions, Srivatsaacelebrations,SIVAKASI will be
            entitled to recover from You, and You agree to pay, all reasonable
            attorneys' fees and costs of such action, in addition to any other
            relief granted to Srivatsaacelebrations.
          </p>
          <h5>M. TERMINATION</h5>
          <p>
            M.1 If You want to terminate your agreement with
            www.Srivatsaacelebrations.com/, you may do so by not accessing the
            website or by closing Your accounts from our website.
          </p>
          <p>
            M.2 www.Srivatsaacelebrations.com/ may, at any time, with or without
            notice, terminate the terms & Conditions (wholly or portion) with
            you if you breach any of the provisions of the Terms & Conditions,
            the Privacy Policy or any other terms, conditions, or policies that
            may be applicable to you from time to time or have acted in a manner
            that clearly shows that you do not intend to, or are unable to,
            comply with the same.
          </p>
          <p>
            M.3 www.Srivatsaacelebrations.com/ may also terminate or suspend all
            or a portion of your account or access to the services with or
            without reason. Termination of your account may include the
            following
          </p>
          <p>
            M.3 a) Removal of access to all offerings within the website or with
            respect to the services.
          </p>
          <p>
            M.3 b) Deletion of your materials and account information, including
            your personal information, log-in ID and password, and all related
            information, files and materials associated with or inside your
            account and
          </p>
          <p>M.3 c) Barring of further use of the services.</p>
          <p>
            M.4 You agree that all terminations shall be made in
            www.Srivatsaacelebrations.com/ sole discretion and that we shall not
            be liable to you or any third party for any termination of your
            account or your access to the website and services.
          </p>
          <h5>N. GOVERNING LAW</h5>
          <p>
            N.1 These terms and conditions and all transactions entered into on
            or through the website and the relationship between you and
            www.Srivatsaacelebrations.com/ shall be governed in accordance with
            the laws of India without reference to conflict of laws principles.
          </p>
          <p>
            N.2 You agree that all claims, differences and disputes arising
            under or in connection with or in relation hereto the website shall
            be subject to the exclusive jurisdiction of the courts at SIVAKASI,
            INDIA and you hereby agree to and accept the jurisdiction of such
            courts.
          </p>
          <h5>O. REPORT ABUSE</h5>
          <p>
            In the event you come across any abuse or violation of these terms
            and conditions or if you become aware of any objectionable content
            on the Website, please report to Srivatsaacelebrations@gmail.Com
          </p>
          <h5>P. FEEDBACK & INFORMATION</h5>
          <p>
            Any feedback you provide to this website shall be deemed to be
            non-confidential. www.Srivatsaacelebrations.com/ shall be free to
            use such information on an unrestricted basis. Further, by
            submitting the feedback, you represent and warrant the following
          </p>
          <p>
            P.1 Your feedback does not include confidential or proprietary
            information of you or third parties.
          </p>
          <p>
            P.2 www.Srivatsaacelebrations.com is under no responsibility of
            secrecy, express or implied, with regard to feedback.
          </p>
          <p>
            P.3 You are not entitled to receive compensation or reimbursement
            from www.Srivatsaacelebrations.com/ for providing feedback under any
            circumstances.
          </p>
          <h5>Q.OFFERS AND DEALS</h5>
          <p>Q.1 Offers cannot be transferred from one account to another.</p>
          <p>Q.2 Coupons cannot be redeemed for cash.</p>
          <p>
            Q.3 The expiration of the offers will depend on the activity it is
            being credited against.
          </p>
          <p>
            Q.4 www.Srivatsaacelebrations.com/ reserves the right to
            decide/alter/change the expiration period of the activities at any
            time with or without notice.
          </p>
          <p>
            Q.5 www.Srivatsaacelebrations.com/ reserves the right to extend or
            terminate the validity of offers and deals associated to any
            activity at any time.
          </p>
          <p>
            Q.6 www.Srivatsaacelebrations.com/ has no obligation to compensate
            the customer after the termination/expiration date of the offers and
            deals.
          </p>
          <p>
            Q.7 www.Srivatsaacelebrations.com/ reserves the right at any time,
            without notice, to add/alter/change/or vary any or all of these
            terms and conditions or to replace, wholly or in part, the offers
            and deals featured on the website or to withdraw it altogether.
          </p>
          <p>
            Q.8 The use of the offers and deals by the customer for redemption
            will be deemed to the acceptance of these Terms and Conditions in
            addition to the rest of the terms and conditions and that the
            customers understand and agree to be unconditionally bound by the
            same.
          </p>
          <p>
            Q.9 www.Srivatsaacelebrations.com/ reserves the right to disqualify
            any customers from the benefits mention herein above. In case of any
            fraudulent activity, prosecution will be carried out against the
            concerned customer.
          </p>
        </div>
      </section>
    </>
  );
};

export default TermsandConditions;
